# Determine the model configuration

# 1) Set overall workflow control parameters
control_parameters:
    multi_period: True
    myopic_horizon: False
    interest_rate: 0.02
    solver: "gurobi"
    fuel_cost_pathway: "NZE"
    fuel_price_shock: "high"
    emissions_cost_pathway: "long-term"
    flexibility_options_scenario: "50"
    activate_emissions_limit: False
    emissions_pathway: "100_percent_linear"
    activate_demand_response: False
    demand_response_approach: "DLR"
    demand_response_scenario: "50"
    impose_investment_maxima: True
    save_production_results: True
    save_investment_results: True
    write_lp_file: False

# 2) Set model optimization time and frequency
time_parameters:
    start_time: "2020-01-01 00:00:00"
    end_time: "2020-01-02 23:00:00"
    freq: "4H"

# 3) Set input and output data paths
input_output_parameters:
    path_folder_input: "./inputs/"
    path_folder_output: "./results/"

# 4) Set rolling (myopic) horizon parameters (optional)
rolling_horizon_parameters:
    myopic_horizon_in_years: 4
    overlap_in_years: 0
