name: pommesinvest
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - pip:
      - git+https://github.com/oemof/oemof-solph.git@feature/account-for-remaining-values-of-multi-period-investments
      - pyyaml