name: pommesinvest
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - pip:
      # TODO: Replace with release when available
      - git+https://github.com/oemof/oemof-solph.git@features/multi-period
      - pyyaml