name: pommesinvest
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - pip:
      - git+https://github.com/oemof/oemof-solph.git@features/fix-investment-results-in-repeated-solving
      - pyyaml